### ISSUE TITLE
Routes inactive?

### ISSUE THREAD

**Issue by sjcjonker** [infowolfe/exabgp-edgerouter#1]
Dear Chip,

May I ask how did you overcome the inactive routes? I'm trying to set this up; but I keep ending up with:
admin@er01:~$ show ip route 8.8.8.8
Routing entry for 8.8.8.8/32
  Known via "bgp", distance 200, metric 0,  External Route Tag: 0
  Last update 00:04:14 ago
    0.0.0.1 inactive

The 0.0.0.1 entry seems right:
sjcjonker@sjc-er01:~$ show ip route 0.0.0.1
Routing entry for 0.0.0.1/32
  Known via "static", distance 1, metric 0,  External Route Tag: 0, best
  * directly connected, Null

Thanks in advance,
Stijn

**Comment by infowolfe** [comment]
I actually haven't done anything with this code in quite some time. Without knowing significantly more about your bgpd config I couldn't tell you why your erlite bgpd isn't activating that route. It could be anything from med/weighting to route policy. My original post on the EdgeRouter forums -should- have included the necessary (for that fw version) configuration details.
