### ISSUE TITLE
loop issue

### ISSUE THREAD

**Issue by Shifty69** [infowolfe/exabgp-edgerouter#2]
Hi,

Great project! I'm testing this for possibly rolling out to a couple of networks we maintain.

However, i'm getting it having a bit of a tizzy whenever upstream remove an ip from the RBL. It will sit there and redownload the rbl from the peer, withdrawing the route every second. Over and over until the process is cleared.

As an example:

Mar  4 19:54:30 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:30 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:31 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:31 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:31 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:31 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:32 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:32 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:32 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:32 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:32 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:32 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:33 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:33 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:33 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:33 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:33 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:33 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:34 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:34 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:34 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:34 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:34 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:34 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:35 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:35 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:35 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:35 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:36 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:36 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:36 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:36 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:36 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:36 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:37 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:37 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:37 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:37 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:37 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:37 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:38 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:38 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:38 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:38 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:38 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:38 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:39 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:39 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:39 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:39 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:40 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:40 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:40 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:40 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666
Mar  4 19:54:40 addisrtr exabgp[7524]: processes     Command from process droproutes : withdraw route 159.65.160.55/32 next-hop self community [64512:666]
Mar  4 19:54:40 addisrtr exabgp[7524]: reactor       Route removed : 159.65.160.55/32 next-hop 10.1.1.200 community 64512:666

My Config hasn't really changed much from the defaults provided apart from the router and local addresses:

#!/usr/bin/env exabgp
group AS64512 {
        router-id 10.1.1.200;
        local-as 64512;
        local-address 10.1.1.200;
        peer-as 64512;

        neighbor 10.1.1.254 {
                family {
                        ipv4 unicast;
                        ipv4 multicast;
                }
        }

        family {
                ipv4 unicast;
                ipv4 multicast;
        }

        process droproutes {
                run /usr/local/bin/blocklists_simple.py;
        }
}

I have set mins to 1440 (IE expire every 24 hours) and sleep to mins * 5

Do you have any ideas where I might start looking?

Thanks!

**Comment by infowolfe** [comment]
I'm sorry, but I haven't actually touched this code in ages. If someone wants to either take it over or send a PR fixing any bugs I'm totally willing to have that happen. It's basically just here for historical purposes.

**Comment by Shifty69** [comment]
Ha all good buddy

Get Outlook for iOS<https://aka.ms/o0ukef>



On Fri, Mar 9, 2018 at 12:25 AM +1300, "Parker" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm sorry, but I haven't actually touched this code in ages. If someone wants to either take it over or send a PR fixing any bugs I'm totally willing to have that happen. It's basically just here for historical purposes.
